keybinding:
  universal:
    quit: q
customCommands:
  - key: "C"
    command: "cz commit"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
