# https://starship.rs/presets/tokyo-night#tokyo-night-preset
# https://www.nerdfonts.com/cheat-sheet

format = """
[  ](bg:#A3AED2 fg:#090c0c)\
$directory\
[](fg:#A3AED2 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 )\
$nodejs\
$python\
\n$character"""

[directory]
style = "fg:#000000 bg:#A3AED2"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "~/"

[directory.substitutions]
"Developer" = ""
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#A3AED2 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#A3AED2 bg:#394260)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[python]
symbol = ""
style = "bg:#212736"
format ='[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )(fg:#769ff0 bg:#212736)]($style)'
