[tools]
node = "lts"
python = "latest"

[settings]
# configure `mise install` to always keep the downloaded archive
always_keep_download = false        # deleted after install by default
always_keep_install = false         # deleted on failure by default
